# Generated by Django 2.2.6 on 2019-12-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai', models.CharField(max_length=255)),
                ('ten_sanpham', models.CharField(max_length=255)),
                ('anh', models.CharField(max_length=255)),
                ('gia', models.IntegerField())
            ],
        ),
    ]
